//! Custom uploaders (a generic HTTP-callback uploader).
//!
//! Sends the image in the multipart field named `profile.file_field`,
//! also carries the token as a separate field if `profile.token_field`
//! is non-empty, and extracts the result URL from the JSON response's
//! `profile.response_field` (dot-separated for nesting).

use serde_json::Value;

use crate::export::Shot;
use crate::store::UploaderProfile;

/// Uploads the image, returning a shareable URL.
pub fn upload(
    shot: &Shot,
    profile: &UploaderProfile,
) -> Result<String, Box<dyn std::error::Error>> {
    let png = crate::export::encode_png(shot)?;
    let boundary = format!("----pashariBoundary{}", unique_suffix());
    let body = build_multipart(&boundary, profile, &png);

    let mut resp = ureq::post(&profile.url)
        .header(
            "Content-Type",
            format!("multipart/form-data; boundary={boundary}"),
        )
        .send(body)?;
    let value: Value = resp.body_mut().read_json()?;
    extract_field(&value, &profile.response_field).ok_or_else(|| -> Box<dyn std::error::Error> {
        format!("レスポンスに '{}' が見つかりません", profile.response_field).into()
    })
}

/// Hand-builds a multipart/form-data body (adds a token field if
/// `token_field` is non-empty, then adds the image under `file_field`).
/// Kept as a pure function so it's unit-testable (the boundary is generated by the caller).
fn build_multipart(boundary: &str, profile: &UploaderProfile, png: &[u8]) -> Vec<u8> {
    let mut body = Vec::new();
    if !profile.token_field.trim().is_empty() {
        body.extend_from_slice(format!("--{boundary}\r\n").as_bytes());
        body.extend_from_slice(
            format!(
                "Content-Disposition: form-data; name=\"{}\"\r\n\r\n",
                profile.token_field
            )
            .as_bytes(),
        );
        body.extend_from_slice(profile.token.as_bytes());
        body.extend_from_slice(b"\r\n");
    }
    body.extend_from_slice(format!("--{boundary}\r\n").as_bytes());
    body.extend_from_slice(
        format!(
            "Content-Disposition: form-data; name=\"{}\"; filename=\"screenshot.png\"\r\n\
             Content-Type: image/png\r\n\r\n",
            profile.file_field
        )
        .as_bytes(),
    );
    body.extend_from_slice(png);
    body.extend_from_slice(b"\r\n");
    body.extend_from_slice(format!("--{boundary}--\r\n").as_bytes());
    body
}

/// Extracts a string value from JSON by walking `path` (dot-separated, e.g. "data.link").
fn extract_field(value: &Value, path: &str) -> Option<String> {
    let mut cur = value;
    for key in path.split('.') {
        cur = cur.get(key)?;
    }
    cur.as_str().map(str::to_string)
}

/// Makes the boundary unique via pid + nanoseconds (same technique as `export::save_temp_png`).
fn unique_suffix() -> u128 {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    nanos + std::process::id() as u128
}

#[cfg(test)]
mod tests {
    use super::*;

    fn profile(token_field: &str, response_field: &str) -> UploaderProfile {
        UploaderProfile {
            name: "test".into(),
            url: "https://example.invalid/upload".into(),
            file_field: "imagedata".into(),
            token_field: token_field.into(),
            token: "tok123".into(),
            response_field: response_field.into(),
            enabled: true,
        }
    }

    #[test]
    fn build_multipart_has_both_fields_and_closing_boundary() {
        let body = build_multipart("BOUND", &profile("access_token", "url"), b"\x89PNGdata");
        let text = String::from_utf8_lossy(&body);

        assert!(text.starts_with("--BOUND\r\n"));
        assert!(
            text.contains(
                "Content-Disposition: form-data; name=\"access_token\"\r\n\r\ntok123\r\n"
            )
        );
        assert!(text.contains(
            "Content-Disposition: form-data; name=\"imagedata\"; filename=\"screenshot.png\"\r\nContent-Type: image/png\r\n\r\n"
        ));
        assert!(text.ends_with("--BOUND--\r\n"));

        // The binary body (PNG) is embedded as-is.
        let needle = b"\x89PNGdata";
        assert!(body.windows(needle.len()).any(|w| w == needle));
    }

    #[test]
    fn build_multipart_omits_token_field_when_empty() {
        let body = build_multipart("BOUND", &profile("", "url"), b"\x89PNGdata");
        let text = String::from_utf8_lossy(&body);
        assert!(!text.contains("tok123"));
        assert!(text.contains("name=\"imagedata\""));
    }

    #[test]
    fn extract_field_reads_top_level_key() {
        let v: Value = serde_json::from_str(r#"{"url":"https://x.test/a"}"#).unwrap();
        assert_eq!(
            extract_field(&v, "url"),
            Some("https://x.test/a".to_string())
        );
    }

    #[test]
    fn extract_field_reads_nested_dot_path() {
        let v: Value = serde_json::from_str(r#"{"data":{"link":"https://x.test/b"}}"#).unwrap();
        assert_eq!(
            extract_field(&v, "data.link"),
            Some("https://x.test/b".to_string())
        );
    }

    #[test]
    fn extract_field_missing_key_returns_none() {
        let v: Value = serde_json::from_str(r#"{"url":"https://x.test/a"}"#).unwrap();
        assert_eq!(extract_field(&v, "nope"), None);
        assert_eq!(extract_field(&v, "nope.deeper"), None);
    }

    #[test]
    fn extract_field_non_string_value_returns_none() {
        let v: Value = serde_json::from_str(r#"{"count":5}"#).unwrap();
        assert_eq!(extract_field(&v, "count"), None);
    }
}
